import BookItem from "../BookItem";
import Header from "../Header";
import { useState, useEffect } from "react";
import { useSearchParams } from "react-router";
import { FiSearch, FiSliders, FiX } from "react-icons/fi";
import "./index.css";
import { additionalBooks, loadCatalog } from "../../data/books";
const BookList = () => { const [params] = useSearchParams(); const [bookList, setBookList] = useState(additionalBooks); const [search, setSearch] = useState(() => params.get("search") || ""); const [sort, setSort] = useState("featured"); useEffect(() => { let current = true; loadCatalog().then((books) => { if (current) setBookList(books); }); return () => { current = false; }; }, []); const books = bookList.filter((book) => `${book.Title} ${book.Author || ""} ${book.category || ""}`.toLowerCase().includes(search.toLowerCase())).sort((a,b) => sort === "price-low" ? Number(a.price)-Number(b.price) : sort === "price-high" ? Number(b.price)-Number(a.price) : sort === "title" ? a.Title.localeCompare(b.Title) : 0); return <div><Header /><main className="catalog-page"><div className="catalog-heading"><p className="eyebrow">The bookshelf</p><h1>Discover your next favorite.</h1><p>Explore our current collection, then make it yours.</p></div><div className="discovery-bar"><label className="search-field"><FiSearch /><input type="search" placeholder="Search by title, author, or category" value={search} onChange={(e) => setSearch(e.target.value)} /></label><label className="sort-field"><FiSliders /><span className="sr-only">Sort books</span><select value={sort} onChange={(e) => setSort(e.target.value)}><option value="featured">Featured</option><option value="title">Title: A–Z</option><option value="price-low">Price: low to high</option><option value="price-high">Price: high to low</option></select></label>{search && <button className="clear-search" onClick={() => setSearch("")}><FiX /> Clear</button>}</div><><p className="results-count">{books.length} {books.length === 1 ? "book" : "books"} found</p>{books.length ? <ul className="book-grid">{books.map((book) => <BookItem bookObj={book} key={book.Id} />)}</ul> : <div className="empty-state"><h2>No books matched that search.</h2><p>Try another title, author, or clear the search.</p><button className="text-button" onClick={() => setSearch("")}>Clear search</button></div>}</></main></div>; };
export default BookList;
