import Header from "../Header";
import BookItem from "../BookItem";
import "./index.css";
import { Link } from "react-router";
import { FiArrowRight, FiBookOpen, FiHeart, FiTruck } from "react-icons/fi";
import { additionalBooks } from "../../data/books";

const Shelf = ({ eyebrow, title, books, action = false }) => <section className="home-shelf"><div className="section-heading"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div>{action && <Link to="/books" className="text-button">View all books <FiArrowRight /></Link>}</div><ul className="home-book-grid">{books.map((book) => <BookItem bookObj={book} key={book.Id} />)}</ul></section>;

const Home = () => <div><Header /><main><section className="hero"><div className="hero-copy"><p className="eyebrow">A better way to find your next read</p><h1>Stories that stay with you.</h1><p className="hero-text">Browse an inspiring, handpicked collection of books for every kind of curious reader.</p><div className="hero-actions"><Link to="/books" className="primary-button">Browse books <FiArrowRight /></Link><a href="#categories" className="text-button">Browse by category</a></div><div className="reader-stats"><span><b>16+</b> curated titles</span><span><b>8</b> categories</span><span><b>Easy</b> checkout</span></div></div><div className="hero-art" aria-hidden="true"><div className="hero-book book-one">READ</div><div className="hero-book book-two">BOOKLE</div><div className="hero-sun" /></div></section><Shelf eyebrow="Handpicked for you" title="Featured books" books={additionalBooks.slice(0,6)} action /><section className="category-section" id="categories"><p className="eyebrow">Explore by interest</p><h2>A shelf for every curiosity.</h2><div className="category-grid">{["Programming & Technology","Self-Development","Business & Finance","Fiction","Psychology","Biography","Science","Productivity"].map((category) => <Link key={category} to={`/books?search=${encodeURIComponent(category)}`}>{category}<FiArrowRight /></Link>)}</div></section><Shelf eyebrow="Reader favorites" title="Popular right now" books={additionalBooks.slice(6,10)} /><Shelf eyebrow="Freshly curated" title="More to discover" books={additionalBooks.slice(10,16)} action /><section className="home-cta"><div><p className="eyebrow">Ready when you are</p><h2>Build a reading list you’ll love.</h2><p>Explore our growing collection and take the next story with you.</p></div><Link to="/books" className="primary-button">Start exploring <FiArrowRight /></Link></section><section className="value-section"><p className="eyebrow">Made for book lovers</p><h2>Find more than a book.</h2><div className="value-grid"><article><FiBookOpen /><h3>Thoughtfully selected</h3><p>Discover titles worth making room for on your shelf.</p></article><article><FiHeart /><h3>Save your favorites</h3><p>Keep a personal reading list ready for later.</p></article><article><FiTruck /><h3>Simple shopping</h3><p>Build your cart and pick up where you left off.</p></article></div></section></main></div>;
export default Home;
